name: Node.js CI

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm ci
    - run: npm run lint
    - run: npm run test:coverage
    - run: npx codecov
      continue-on-error: true
