name: Node.js CI/CD flows

on:
  push

jobs:
  build:

    runs-on: self-hosted-runner

    

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm ci
    - run: npm run lint
    - run: npm run test:coverage
    - run: npx codecov
      continue-on-error: true
    - name: Build application
      run: npm run build
    - uses: actions/upload-artifact@v4.6.0
      with:
       name: build-artifact
       path: ./
